apiVersion: v1
kind: Service
metadata:
  name: moods-service-service
  labels:
    app: moods-service
spec:
  type: ClusterIP
  selector:
    app: moods-service
  ports:
  - port: 50052
    targetPort: 50052