apiVersion: apps/v1
kind: Deployment
metadata:
  name: entries-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: entries
  template:
    metadata:
      labels:
        component: entries
    spec:
      containers:
        - name: entries
          image: prashantdey/merndemoapp:entriesv1.0
          ports:
            - containerPort: 50051
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD

