apiVersion: v1
kind: Service
metadata:
  name: stats-service-service
  labels:
    app: stats-service
spec:
  type: ClusterIP
  selector:
    app: stats-service
  ports:
  - port: 50053
    targetPort: 50053